CREATE DATABASE IF NOT EXISTS ih_login_server;
CREATE DATABASE IF NOT EXISTS ih_hall_server;
CREATE DATABASE IF NOT EXISTS ih_hall_server_2;
CREATE DATABASE IF NOT EXISTS ih_hall_server_3;
CREATE DATABASE IF NOT EXISTS ih_hall_server_4;
