//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: client_message.proto
namespace msg.client_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CErrCode")]
  public partial class S2CErrCode : global::ProtoBuf.IExtensible
  {
    public S2CErrCode() {}
    
    private int _ErrorCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ErrorCode
    {
      get { return _ErrorCode; }
      set { _ErrorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SLoginRequest")]
  public partial class C2SLoginRequest : global::ProtoBuf.IExtensible
  {
    public C2SLoginRequest() {}
    
    private string _acc = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"acc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string acc
    {
      get { return _acc; }
      set { _acc = value; }
    }
    private string _token = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CLoginResponse")]
  public partial class S2CLoginResponse : global::ProtoBuf.IExtensible
  {
    public S2CLoginResponse() {}
    
    private long _PlayerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"E_VERSION")]
    public enum E_VERSION
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_VERSION_NUMBER", Value=1101)]
      E_VERSION_NUMBER = 1101
    }
  
}

namespace msg.client_message
{
	public partial class S2CErrCode : global::ProtoBuf.IExtensible
	{
		public static readonly ushort MessageTypeId = 1;
	}
	
	public partial class C2SLoginRequest : global::ProtoBuf.IExtensible
	{
		public static readonly ushort MessageTypeId = 2;
	}
	
	public partial class S2CLoginResponse : global::ProtoBuf.IExtensible
	{
		public static readonly ushort MessageTypeId = 3;
	}
	
	public class MessageTypeManager
	{
		public static System.Collections.Generic.Dictionary<ushort, string> MessageNames=new System.Collections.Generic.Dictionary<ushort, string>();
		static MessageTypeManager()
		{
			MessageNames.Add(1,"S2CErrCode");
			MessageNames.Add(2,"C2SLoginRequest");
			MessageNames.Add(3,"S2CLoginResponse");
			MessageNames.Add(0xFFFF,"ACK");
		}
	}
}
