// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db_center.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db_center.proto

It has these top-level messages:
	IdNum
	ServerRewardRewardInfo
	ServerRewardRewardInfoList
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IdNum struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Num              *int32 `protobuf:"varint,2,opt,name=Num" json:"Num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IdNum) Reset()                    { *m = IdNum{} }
func (m *IdNum) String() string            { return proto.CompactTextString(m) }
func (*IdNum) ProtoMessage()               {}
func (*IdNum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IdNum) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *IdNum) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type ServerRewardRewardInfo struct {
	RewardId         *int32   `protobuf:"varint,1,opt,name=RewardId" json:"RewardId,omitempty"`
	Items            []*IdNum `protobuf:"bytes,2,rep,name=Items" json:"Items,omitempty"`
	Channel          *string  `protobuf:"bytes,3,opt,name=Channel" json:"Channel,omitempty"`
	EndUnix          *int32   `protobuf:"varint,4,opt,name=EndUnix" json:"EndUnix,omitempty"`
	Content          *string  `protobuf:"bytes,5,opt,name=Content" json:"Content,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ServerRewardRewardInfo) Reset()                    { *m = ServerRewardRewardInfo{} }
func (m *ServerRewardRewardInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerRewardRewardInfo) ProtoMessage()               {}
func (*ServerRewardRewardInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerRewardRewardInfo) GetRewardId() int32 {
	if m != nil && m.RewardId != nil {
		return *m.RewardId
	}
	return 0
}

func (m *ServerRewardRewardInfo) GetItems() []*IdNum {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ServerRewardRewardInfo) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *ServerRewardRewardInfo) GetEndUnix() int32 {
	if m != nil && m.EndUnix != nil {
		return *m.EndUnix
	}
	return 0
}

func (m *ServerRewardRewardInfo) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type ServerRewardRewardInfoList struct {
	List             []*ServerRewardRewardInfo `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ServerRewardRewardInfoList) Reset()                    { *m = ServerRewardRewardInfoList{} }
func (m *ServerRewardRewardInfoList) String() string            { return proto.CompactTextString(m) }
func (*ServerRewardRewardInfoList) ProtoMessage()               {}
func (*ServerRewardRewardInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServerRewardRewardInfoList) GetList() []*ServerRewardRewardInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*IdNum)(nil), "db.IdNum")
	proto.RegisterType((*ServerRewardRewardInfo)(nil), "db.ServerRewardRewardInfo")
	proto.RegisterType((*ServerRewardRewardInfoList)(nil), "db.ServerRewardRewardInfoList")
}

func init() { proto.RegisterFile("db_center.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8e, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x49, 0xba, 0x45, 0x77, 0x04, 0x95, 0x1c, 0x64, 0xe8, 0xc5, 0xd2, 0x53, 0xbd, 0xe4,
	0xe0, 0x5f, 0x10, 0x0f, 0x81, 0x65, 0x0f, 0x11, 0xcf, 0xb2, 0x75, 0x46, 0x5c, 0xb0, 0x13, 0xc9,
	0x66, 0xd5, 0xff, 0xe3, 0x1f, 0x95, 0xa4, 0x5b, 0x4f, 0xbd, 0x24, 0xf9, 0x26, 0xef, 0xbd, 0x79,
	0x70, 0x45, 0xc3, 0xcb, 0x2b, 0x4b, 0xe2, 0x68, 0x3f, 0x63, 0x48, 0xc1, 0x68, 0x1a, 0xba, 0x3b,
	0xa8, 0x1d, 0x6d, 0x8f, 0xa3, 0xb9, 0x04, 0xed, 0x08, 0x55, 0xab, 0xfa, 0xda, 0x6b, 0x47, 0xe6,
	0x1a, 0xaa, 0xed, 0x71, 0x44, 0x5d, 0x06, 0xf9, 0xd9, 0xfd, 0x2a, 0xb8, 0x79, 0xe2, 0xf8, 0xc5,
	0xd1, 0xf3, 0xf7, 0x2e, 0xd2, 0x74, 0x3a, 0x79, 0x0b, 0xa6, 0x81, 0xf3, 0x13, 0xcd, 0x11, 0xff,
	0x6c, 0x6e, 0xa1, 0x76, 0x89, 0xc7, 0x03, 0xea, 0xb6, 0xea, 0x2f, 0xee, 0xd7, 0x96, 0x06, 0x5b,
	0x56, 0xfa, 0x69, 0x6e, 0x10, 0xce, 0x1e, 0xde, 0x77, 0x22, 0xfc, 0x81, 0x55, 0xab, 0xfa, 0xb5,
	0x9f, 0x31, 0xff, 0x3c, 0x0a, 0x3d, 0xcb, 0xfe, 0x07, 0x57, 0x25, 0x75, 0xc6, 0xe2, 0x09, 0x92,
	0x58, 0x12, 0xd6, 0x27, 0xcf, 0x84, 0xdd, 0x06, 0x9a, 0xe5, 0x92, 0x9b, 0xfd, 0x21, 0x19, 0x0b,
	0xab, 0x7c, 0xa3, 0x2a, 0x5d, 0x9a, 0xdc, 0x65, 0x59, 0xed, 0x8b, 0xee, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0x74, 0x09, 0xa5, 0x34, 0x01, 0x00, 0x00,
}
